apiVersion: apps/v1
kind: Deployment
metadata:
  name: iammanju-commafeed
  namespace: iammanju-commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000      