apiVersion: v1
kind: Service
metadata:
  name: iammanju-commafeed
  namespace: iiammanju-commafeed
spec:
  ports:
  - name: web-ui
    port: 8083
    targetPort: 8083
  selector:
    app.iammanju.io/name: "commafeed"